export const PHOTOS_REQUEST = "PHOTOS_REQUEST";
export const PHOTOS_SUCCESS = "PHOTOS_SUCCESS";
export const PHOTOS_FAILURE = "PHOTOS_FAILURE";

export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";

export const PHOTO_REQUEST = "PHOTO_REQUEST";
export const PHOTO_SUCCESS = "PHOTO_SUCCESS";
export const PHOTO_FAILURE = "PHOTO_FAILURE";

export const QUERY_SEARCH = "QUERY_SEARCH";
